### ISSUE TITLE
Is it possible to use globbing pattern in path?

### ISSUE THREAD

**Issue by p16i** [mapsherpa/grunt-touch#1]
For ex.

```
module.exports = {
    options: {
      force: true,
      mtime: true
    },
    src: [
        'app/sass/*',
    ]
};

```

**Comment by palnes** [comment]
Does grunt-touch support file-name globbing, as defined https://github.com/gruntjs/grunt/wiki/Configuring-tasks#globbing-patterns ?

**Comment by chrisguttandin** [comment]
Sorry. I didn't see this before making the pull request. My pull request should allow those file definitions.
